### ISSUE TITLE
Esri REST Service to OpenTrails Converter

### ISSUE THREAD

**Issue by lyzidiamond** [opentraildata/opentrails-project-ideas#10]
Just like the current OT converter, except it can take the URL of a REST endpoint and export as OpenTrails. Bonus if it also does field matching! :penguin: :dolphin: :bowtie:

**Comment by todrobbins** [comment]
@lyzidiamond was this issue closed by a specific pull request or was it abandoned for now?

**Comment by lyzidiamond** [comment]
Closed because stale. If you'd like to pick it up feel free!
